name = "SimpleRegistry"
uuid = "1b4ed4a1-e93f-4662-97fb-5681e0f87e83"
repo = "https://github.com/vdayanand/SimpleRegistry"
description = "a test registry"

[packages]
7876af07-990f-54b4-ab0e-23690620f79b = { name = "PrivateExample3", path = "P/PrivateExample3" }
9b87118b-4619-50d2-8e1e-99f35a4d4d9d = { name = "PackageCompiler", path = "P/PackageCompiler" }
