name = "SimpleRegistry"
uuid = "1b4ed4a1-e93f-4662-97fb-5681e0f87e83"
repo = "https://github.com/vdayanand/SimpleRegistry"
description = "a test registry"

[packages]
7876af07-991d-54b4-ab0e-23690620f79b = { name = "PrivateExample", path = "P/PrivateExample" }
